export const PEEKS_B: Record<string, { kicker: string; text: string }[]> = {
  zacchaeus: [
    { kicker: "Too short", text: "Zacchaeus was short, and people did not like him much. He climbed a tree to see Jesus." },
    { kicker: "Looked up", text: "Jesus stopped under that tree. He looked up. He called Zacchaeus by name." },
    { kicker: "Come down", text: "\u201cCome down,\u201d Jesus said. \u201cI am coming to your house today.\u201d Zacchaeus hurried down, glad." },
    { kicker: "Changed", text: "Meeting Jesus changed him. Jesus sees every heart and calls each one by name." },
  ],
  "the-good-samaritan": [
    { kicker: "A hard road", text: "A man was hurt on the road. Some people walked past. They were busy. They did not stop." },
    { kicker: "Someone stopped", text: "A Samaritan stopped. He cleaned the man's wounds. He put him on his own donkey." },
    { kicker: "An inn", text: "He paid for a room and promised to come back. Kindness cost him time and coins." },
    { kicker: "Go and do likewise", text: "Jesus said love looks like stopping. Love helps, even when the road is hard." },
  ],
  "the-feeding-of-the-5000": [
    { kicker: "Hungry people", text: "A huge crowd had listened to Jesus all day. Evening came. Tummies rumbled." },
    { kicker: "A small lunch", text: "A child had five loaves and two fish. It did not look like enough. The child gave it anyway." },
    { kicker: "Jesus thanked God", text: "Jesus took the little lunch, thanked God, and began to share. Baskets filled. Baskets overflowed." },
    { kicker: "More than enough", text: "When we offer what we have, Jesus makes more than enough." },
  ],
  "adam-and-eve-in-the-garden": [
    { kicker: "A garden", text: "God planted a beautiful garden and put Adam and Eve there to care for it and walk with Him." },
    { kicker: "One tree", text: "They could eat from every tree but one. A sneaky voice said, \u201cJust one bite.\u201d" },
    { kicker: "Hid", text: "They hid. The garden felt different. God came walking in the cool of the day and called their names." },
    { kicker: "Still loved", text: "Even after they disobeyed, God still loved them. God does not stop looking for us." },
  ],
  "joshua-and-jericho": [
    { kicker: "Tall walls", text: "Jericho had tall walls. Joshua's army did not look big enough. God had a strange plan." },
    { kicker: "Walk", text: "For six days they walked around the city. No shouting. Just walking, and trusting." },
    { kicker: "The seventh day", text: "On the seventh day they walked seven times. Then they shouted, and the walls fell down." },
    { kicker: "Trust the plan", text: "God's ways are not always our ways. Sometimes the brave thing is to keep walking." },
  ],
  "the-fiery-furnace": [
    { kicker: "Bow down", text: "The king built a tall statue and said, \u201cBow.\u201d Shadrach, Meshach, and Abednego would bow only to God." },
    { kicker: "The furnace", text: "The king was angry. He had the furnace heated extra hot. Still they would not bow." },
    { kicker: "Four people", text: "They were thrown in \u2014 and the king saw four people walking in the fire, unhurt. God was with them." },
    { kicker: "Not alone", text: "When we stand for God, we are never standing by ourselves." },
  ],
  "the-prodigal-son": [
    { kicker: "Far away", text: "A younger son took his share and went far from home. He spent it all. He grew hungry and sorry." },
    { kicker: "I will go home", text: "He practiced a speech. \u201cI am not worthy.\u201d He started the long walk back." },
    { kicker: "Running", text: "While he was still a long way off, his father saw him and ran. He hugged him before the speech was done." },
    { kicker: "Welcome home", text: "Jesus said God is like that father. You can always come home." },
  ],
  "the-wedding-at-cana": [
    { kicker: "A wedding", text: "Jesus went to a wedding with His mother and His friends. People were glad. Then the wine ran out." },
    { kicker: "Do what He says", text: "Mary told the servants, \u201cDo whatever He tells you.\u201d Jesus asked for six big stone jars." },
    { kicker: "Water", text: "They filled the jars with water. When they poured, it was not water anymore." },
    { kicker: "The best", text: "Jesus' first miracle was kindness at a party. He still turns empty into enough." },
  ],
  "hannahs-prayer-and-young-samuel": [
    { kicker: "Hannah prayed", text: "Hannah wanted a child. She prayed so hard that her lips moved and no sound came out. God heard." },
    { kicker: "Samuel", text: "God gave her Samuel. When he was old enough, Hannah kept her promise and brought him to serve God." },
    { kicker: "Speak, Lord", text: "One night God called, \u201cSamuel!\u201d An old priest helped him answer, \u201cSpeak, Lord. I am listening.\u201d" },
    { kicker: "Little listeners", text: "God speaks to children. A listening heart is a brave heart." },
  ],
  "saul-becomes-paul": [
    { kicker: "Angry Saul", text: "Saul was sure he was right. He was unkind to people who loved Jesus." },
    { kicker: "A bright light", text: "On the road, a light brighter than the sun stopped him. Jesus spoke his name." },
    { kicker: "New eyes", text: "For three days Saul could not see. Then God gave him new eyes \u2014 and a new heart." },
    { kicker: "Paul", text: "Saul became Paul, who told the whole world about Jesus. God can change anyone." },
  ],
  "paul-and-silas-in-prison": [
    { kicker: "Midnight", text: "Paul and Silas were in prison. Their feet were in stocks. At midnight they sang." },
    { kicker: "An earthquake", text: "The ground shook. Doors opened. Chains fell off. The jailer was afraid." },
    { kicker: "Don't go", text: "Paul called out, \u201cWe are all here!\u201d He did not run. He stayed to help." },
    { kicker: "A new family", text: "That night the jailer's whole household believed. Songs in the dark still matter." },
  ],
  "pentecost-the-holy-spirit-comes": [
    { kicker: "Waiting", text: "Jesus' friends waited together in a room. Jesus had promised a Helper." },
    { kicker: "Wind and flame", text: "A sound like a strong wind filled the house. Something like fire rested on each of them." },
    { kicker: "Every language", text: "They spoke, and people from many places understood \u2014 God was near, in words they knew." },
    { kicker: "The Helper", text: "The Holy Spirit had come. God does not leave His children to do hard things alone." },
  ],
  "elisha-and-the-widows-oil": [
    { kicker: "Empty jars", text: "A widow had almost nothing left \u2014 just a little oil, and bills she could not pay." },
    { kicker: "Borrow jars", text: "Elisha said, \u201cBorrow empty jars. As many as you can.\u201d She and her boys gathered them." },
    { kicker: "Pour", text: "She poured the little oil. It kept coming. Jar after jar filled, until there were no jars left." },
    { kicker: "Enough", text: "God can fill empty places. Bring what you have. He knows how to make it enough." },
  ],
  "tower-of-babel": [
    { kicker: "One language", text: "Long ago everyone spoke the same words. They said, \u201cLet us build a tower up to the sky.\u201d" },
    { kicker: "Our name", text: "They wanted to make a name for themselves. They were not asking what God wanted." },
    { kicker: "Scattered", text: "God mixed up their words. The building stopped. People went different ways." },
    { kicker: "God knows best", text: "Big plans without God fall down. Little hearts can ask Him first." },
  ],
  "gideons-tiny-army": [
    { kicker: "Too small", text: "Gideon felt too small. God said, \u201cI am sending you.\u201d Gideon still asked for signs." },
    { kicker: "Too many", text: "God made the army smaller. Then smaller again. Only a handful left." },
    { kicker: "Jars and trumpets", text: "They did not win with big swords. They held jars, torches, and trumpets, and trusted God." },
    { kicker: "Enough", text: "When God is on your side, you are enough \u2014 even if you feel tiny." },
  ],
  "nehemiah-builds-the-wall": [
    { kicker: "Broken walls", text: "Nehemiah heard that his city's walls were broken. He sat down and cried. Then he prayed." },
    { kicker: "Ask and plan", text: "He asked the king for help. He made a plan. He rode out at night to see the rubble." },
    { kicker: "Work together", text: "Families each took a section. Some built. Some guarded. The wall rose, bit by bit." },
    { kicker: "Finished", text: "Pray, plan, and work. God helps us finish what matters." },
  ],
  "jesus-walks-on-water": [
    { kicker: "A long night", text: "The friends were in the boat, far from land. The wind was against them. Jesus was not in the boat." },
    { kicker: "On the water", text: "They saw someone walking on the waves. They were afraid. Jesus said, \u201cIt is I. Don't be afraid.\u201d" },
    { kicker: "Peter", text: "Peter stepped out. For a moment he walked too. Then he looked at the wind and began to sink." },
    { kicker: "Jesus reached", text: "Jesus reached out at once and held him. When we get scared, He is already close." },
  ],
  "lazarus-comes-out": [
    { kicker: "A sad house", text: "Lazarus was sick, then Lazarus died. Mary and Martha were brokenhearted. Jesus came late, they thought." },
    { kicker: "Jesus wept", text: "Jesus cried with them. God does not shrug at our sad days." },
    { kicker: "The tomb", text: "At the tomb Jesus called in a loud voice, \u201cLazarus, come out!\u201d" },
    { kicker: "Alive", text: "The man who had died came out, still wrapped in cloth. Jesus is stronger than the worst goodbye." },
  ],
};
