export const PEEKS_A: Record<string, { kicker: string; text: string }[]> = {
  "noah-and-gods-big-promise": [
    { kicker: "Noah loved God", text: "A long, long time ago, there lived a man named Noah. Noah loved God with all his heart. One day God said, \u201cI need you to do something big. Build a very, very big boat.\u201d Noah looked around. There was no water nearby. But Noah trusted God." },
    { kicker: "Two by two", text: "When the Ark was ready, God said, \u201cNow bring the animals, Noah.\u201d Two by two they came. Big ones and small ones. Tall ones and fluffy ones. Noah welcomed them all. \u201cCome in, come in,\u201d he said with a smile." },
    { kicker: "The rain", text: "Then the rain began. First a little. Then a lot. The water rose higher and higher. But inside the Ark, everyone was safe and warm. For many days it rained. But Noah was not afraid. He trusted God's promise." },
    { kicker: "A rainbow", text: "Noah looked up at the sky. And there it was \u2014 a beautiful rainbow. God spoke again. \u201cNoah, this rainbow is my promise. I will care for the world I made.\u201d When you see a rainbow, remember \u2014 God keeps His promises." },
  ],
  "david-and-the-giant": [
    { kicker: "A small shepherd", text: "David was not the biggest brother. He was not the tallest soldier. He was a shepherd who sang to God in the fields." },
    { kicker: "A very big shout", text: "A giant named Goliath shouted at God's people. Everyone felt small. David felt small too. But he remembered who God is." },
    { kicker: "Five smooth stones", text: "David picked up five smooth stones. He did not wear heavy armor. He ran toward the giant with a sling and a prayer." },
    { kicker: "God is bigger", text: "The giant fell. The people cheered. David learned a true thing: even when we feel small, God is bigger than every giant." },
  ],
  "jonah-and-the-big-fish": [
    { kicker: "Runaway", text: "God told Jonah, \u201cGo.\u201d Jonah said, \u201cNo.\u201d He ran the other way and climbed onto a boat." },
    { kicker: "A storm", text: "Wind whipped the waves. The sailors were afraid. Jonah knew the storm had followed him. He asked to be thrown into the sea." },
    { kicker: "A great fish", text: "God sent a great fish to swallow Jonah \u2014 not to end the story, but to keep him. In the dark, Jonah prayed." },
    { kicker: "Second chance", text: "The fish spit Jonah onto the sand. God still had a job for him. God does not give up on us." },
  ],
  "the-christmas-story": [
    { kicker: "A long road", text: "Mary and Joseph walked a long, dusty road to Bethlehem. There was no room in the inn. Only a quiet place with animals." },
    { kicker: "A baby", text: "That night, Jesus was born. Mary wrapped Him in cloth and laid Him in a manger. Heaven had come close." },
    { kicker: "A bright field", text: "Shepherds were watching their sheep when the sky filled with song. \u201cDo not be afraid. A Savior is born.\u201d" },
    { kicker: "Come close", text: "They hurried to see the baby. God came close in love \u2014 close enough for little hearts to hold." },
  ],
  "the-easter-story": [
    { kicker: "A sad Friday", text: "Jesus loved us all the way to the cross. His friends were sad. The sky felt heavy. It seemed like the story was over." },
    { kicker: "A still Saturday", text: "Jesus' body was laid in a tomb. A stone was rolled across the door. His friends waited, and the waiting was quiet." },
    { kicker: "Sunday morning", text: "Very early, the women came to the garden. The stone was rolled away. The tomb was empty. An angel said, \u201cHe is not here.\u201d" },
    { kicker: "Alive", text: "Jesus was alive. God's greatest rescue had come. Hope is not a maybe. Hope has a name." },
  ],
  "the-lost-sheep": [
    { kicker: "Ninety-nine", text: "A shepherd had one hundred sheep. At sundown he counted: ninety-eight, ninety-nine\u2026 one was missing." },
    { kicker: "The search", text: "He left the ninety-nine in a safe place and went looking. Over rocks. Through thorns. He would not stop." },
    { kicker: "Found", text: "At last he heard a tiny bleat. He lifted the lost sheep onto his shoulders. He was not angry. He was glad." },
    { kicker: "Carried home", text: "Jesus said He is like that shepherd. He knows your name. He comes to find you and carries you home with joy." },
  ],
  "the-creation-story": [
    { kicker: "Let there be light", text: "At first it was dark and empty. Then God spoke. Light spilled out. Day and night began." },
    { kicker: "Sky, sea, and seed", text: "God made sky like a wide blue tent. He gathered the seas. He filled the land with trees, fruit, and flowers." },
    { kicker: "Living things", text: "Fish flashed in the water. Birds stitched the air. Animals walked the garden. God saw that it was good." },
    { kicker: "People He loves", text: "Then God made people in His image \u2014 to care for the world and walk with Him. You are part of this good beginning." },
  ],
  "jesus-welcomes-children": [
    { kicker: "Busy grown-ups", text: "Parents brought their children to Jesus. Some grown-ups frowned. \u201cHe is too busy,\u201d they said. \u201cNot now.\u201d" },
    { kicker: "Jesus saw them", text: "Jesus was not too busy. He was not annoyed. He stopped what He was doing and opened His arms." },
    { kicker: "Come", text: "\u201cLet the little children come to me,\u201d Jesus said. \u201cDo not send them away. The kingdom of God belongs to ones like these.\u201d" },
    { kicker: "Held", text: "He took the children in His arms and blessed them. You do not have to wait until you are bigger. You are welcome now." },
  ],
  "moses-and-the-red-sea": [
    { kicker: "Trapped", text: "God's people stood at the edge of the sea. The army was behind them. There was no path. They were afraid." },
    { kicker: "Stretch out your hand", text: "Moses listened to God. He stretched his hand over the water. The sea did not stay shut." },
    { kicker: "A dry road", text: "The water stood up like walls. A dry road opened through the middle. God's people walked forward, one step at a time." },
    { kicker: "Safe", text: "When they reached the other side, they sang. God can make a way when there seems to be no way." },
  ],
  "daniel-and-the-lions": [
    { kicker: "A window", text: "Daniel loved God. Three times a day he opened his window and prayed \u2014 even when a new rule said he must not." },
    { kicker: "The den", text: "The king liked Daniel, but the rule was the rule. Daniel was lowered into a den of lions." },
    { kicker: "All night", text: "The king could not sleep. In the dark, Daniel was not alone. God sent an angel to shut the lions' mouths." },
    { kicker: "Morning", text: "At sunrise Daniel was unhurt. God stays close when we are brave enough to keep praying." },
  ],
  "esther-the-brave-queen": [
    { kicker: "A quiet girl", text: "Esther became queen, but she kept a secret. God's people were in danger, and she was afraid to speak." },
    { kicker: "For such a time", text: "Her cousin Mordecai said, \u201cPerhaps you are queen for such a time as this.\u201d Esther asked her people to pray." },
    { kicker: "I will go", text: "Esther put on her royal clothes and went to the king \u2014 even though it was dangerous to go uninvited." },
    { kicker: "Courage", text: "She spoke up, and her people were saved. Little brave hearts can change a whole story." },
  ],
  "josephs-colorful-coat": [
    { kicker: "A gift", text: "Father Jacob loved Joseph and gave him a coat of many colors. Joseph's brothers were not glad." },
    { kicker: "Far from home", text: "They sent Joseph far away. The coat was gone. The home he knew was gone. But God had not gone." },
    { kicker: "In Egypt", text: "Years later Joseph helped a whole land through hungry days. The boy in the colorful coat had become a helper." },
    { kicker: "Forgiven", text: "When his brothers came, Joseph forgave them. What others meant for harm, God could use for good." },
  ],
  "ruth-and-naomi": [
    { kicker: "Two roads", text: "Naomi's life had grown sad. She told Ruth to go home. Ruth would not leave her." },
    { kicker: "Where you go", text: "\u201cWhere you go, I will go,\u201d Ruth said. \u201cYour people will be my people. Your God will be my God.\u201d" },
    { kicker: "The field", text: "In a new town, Ruth gathered leftover grain. Boaz was kind. God was quietly making a family." },
    { kicker: "Loyal love", text: "Ruth stayed. God stayed. Loyal love is a kind of courage little hearts can practice." },
  ],
  "the-birth-of-moses": [
    { kicker: "A hidden baby", text: "A new baby boy was born when it was dangerous to be a baby boy. His mother hid him as long as she could." },
    { kicker: "A basket", text: "She made a little basket, lined it with love, and set it among the reeds of the river." },
    { kicker: "A sister watching", text: "Miriam watched. A princess found the basket. The baby cried, and her heart opened." },
    { kicker: "Kept", text: "Moses was kept safe. God watches over little lives, even in a river basket." },
  ],
  "solomon-and-wisdom": [
    { kicker: "A new king", text: "Solomon was young when he became king. One night God said, \u201cAsk Me for anything.\u201d" },
    { kicker: "Not gold", text: "Solomon did not ask for gold. He did not ask to be famous. He asked for a listening heart." },
    { kicker: "Wisdom", text: "God was pleased. He gave Solomon wisdom \u2014 and more besides." },
    { kicker: "Ask well", text: "The best things to ask God for are the things that help us love people well." },
  ],
  "elijah-and-the-still-small-voice": [
    { kicker: "Tired", text: "Elijah had been brave, and now he was tired. He sat under a tree and felt very small." },
    { kicker: "Wind, fire, shake", text: "A wind roared. The ground shook. Fire flashed. God was not in the noise." },
    { kicker: "A whisper", text: "Then came a still, small voice. God was close. God was kind. God still had work for Elijah." },
    { kicker: "Listen", text: "Sometimes God speaks in the quiet. Little hearts can listen too." },
  ],
  "jesus-calms-the-storm": [
    { kicker: "A boat", text: "Jesus and His friends set out across the water. Jesus fell asleep on a cushion." },
    { kicker: "Waves", text: "A storm rose fast. Waves climbed into the boat. The friends shook Him. \u201cDon't You care?\u201d" },
    { kicker: "Peace, be still", text: "Jesus stood up. He spoke to the wind and the sea. \u201cPeace. Be still.\u201d And they were." },
    { kicker: "Who is this?", text: "The friends whispered, \u201cWho is this?\u201d Even the weather listens to Jesus." },
  ],
  "the-armor-of-god": [
    { kicker: "Getting dressed", text: "God gives His children special things to put on \u2014 not heavy metal, but true help." },
    { kicker: "Belt and shoes", text: "Truth like a belt. Peace like shoes, so we can walk into the day without fear." },
    { kicker: "Shield and helmet", text: "Faith like a shield. Salvation like a helmet. God's Word close enough to hold." },
    { kicker: "Ready", text: "We do not fight mean. We stand kind and brave, because God is with us." },
  ],
};
